# Site settings
title: Ashish Singh
description: Personal Site
baseurl: "/" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ashish Singh
user_description: ğŸ‘‹ Hi, my name is Ashish and I'm from India.

ğŸ‘¨â€ğŸ’» I'm a Windows focused Software developer.

ğŸ’» I like checking out open source projects and sharing my own code on Github.

ğŸ‘¥ I have experience working in agile environments and am a convinced advocate of clean code.

ğŸ¤– I automate repetitive processes on my computer via bash or python scripting.

ğŸ“ˆ I am passionate about investing and I'm planning to share my experiences on a blog later on.
user_title: Software Developer
email: ashish855116@gmail.com
twitter_username: lorem_ipsum
github_username:  TechNinja69

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
